import express from 'express';
import { fetchUser } from '../middleware/fetchUser.js';
import UserNotification from '../Models/UserNotification.js';
const router = express.Router();

// 1 => Get All User Notifications generated by admin using the GET request: http://localhost:3000/notification/getAll
router.get('/getAll', fetchUser, async (req, res) => {
    try {
        const userid = req.user.userID;

        const notification = await UserNotification.find({ user: userid });

        res.send(notification);

    } catch (err) {
        res.status(500).json({ error: err.message });
    }
})

export default router;